# .github/workflows/daily_run.yml

name: "Run Daily Workout Planner"

on:
  # Schedule to run every day at 22:00 UTC (10:00 PM UTC)
  schedule:
    - cron: '0 5 * * *'
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  run-python-script:
    runs-on: ubuntu-latest

    steps:
      # 1. Checks out your repository's code so the job can access it
      - name: Check out repository code
        uses: actions/checkout@v4

      # 2. Sets up the Python version you want to use
      - name: Set up Python 3.11
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      # 3. Installs your script's dependencies from requirements.txt
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      # 4. Runs your main Python script
      - name: Execute Python script
        env:
          # Makes the GitHub secrets available as environment variables to the script
          API_KEY: ${{ secrets.API_KEY }}
          ATHLETE_ID: ${{ secrets.ATHLETE_ID }}
        run: python main.py
